### ISSUE TITLE
Add ability to send 'filter_id' field to Mortech

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-mortech#11]
We require the option to send a custom string field to Mortech. This should match the functionality in Velocify to send a custom field in a post.

**Comment by zalary** [comment]
Mortech, has a set of fields that they generally allow, so allowing users to set a bunch of custom fields doesn't seem necessary.  

is there a specific field that needs to be added?  Is it going to be mapped to data from a specific source or multiple sources? (could the Mortech integration handle the mapping so it doesn't have to be field mapping the user sets up?)

**Comment by kcaponeAP** [comment]
We've had a few discussions lately with Mortech and clients who are wishing to do custom routing. So this would solve that issue. 

Regarding the name of this particular field, its: filter_id.

**Comment by kcaponeAP** [comment]
I think it's also due to the fact that we haven't added every field that Mortech offers since if it didn't have a corresponding internal LCN field, it was omitted.

**Comment by zalary** [comment]
I guess I would ask, which clients and which fields are they wanting to custom route?  The point of integrations is to take the onus off of clients to do mappings. If there are lots of unaccounted for fields that users can't handle with an integration, then the integration loses value.  If there are multiple fields that fall under mortgage that need to be mapped, we should do that for users.  If there really are lots of different fields that need to be mapped on a one off basis, we should discuss that and adjust accordingly, but it seems premature to do that now based on my current understanding of the Mortech setup.

**Comment by alexkwolfe** [comment]
One thing we've been considering is automatically sending all mapped values to an integration (this would apply to all integrations, not just Mortech). That would mean that for services such as Mortech that allow collection of non-standard fields, the user would simply have to add a mapping for their custom data in order for it be sent.

This arrangement would obviate the need for custom request variable naming schemes like `mortech.custom.filter_id`.

@kcaponeAP, what is the `filter_id` field? It sounds suspiciously like the `lendingtree.filter_id` field to me.

**Comment by alexkwolfe** [comment]
I agree with @zalary's premise that we should strive to make as many of the mappings as possible automatic. That requires careful consideration of every request to add a custom field to an integration. 

Once we allow users to pass whatever they want through the integration, it will be more difficult to be involved in those decisions (at least insofar as the customer is configuring their own account).

**Comment by kcaponeAP** [comment]
In this particular arrangement, the way the customer has it set up is as follows:

Lendingtree Filter Name routes to mortech.filter_id

**Comment by kcaponeAP** [comment]
I absolutely agree with Zal too. But how do we handle the edge cases that are requirements in the customer's eyes?

**Comment by alexkwolfe** [comment]
I'm not sure this is feasible in this situation, but the best scenario here would be to route our `lendingtree.filter_name` to an appropriately named field in Mortech (say `lendingtree_filter_id`). Then we could tell all our Mortech customers that if they want to capture the LendingTree filter name, that they need to add the custom field called `lendingtree_filter_name`.

**Comment by alexkwolfe** [comment]
Sorry. There was a typo in that last message. I've corrected it in github.

**Comment by alexkwolfe** [comment]
If that isn't possible, then we're going to have to do what you've suggested @kcaponeAP and come back later to fix it up.

**Comment by zalary** [comment]
by helping our customers make good setups?  If people who buy Velocify leads want the filter name, ideally we could set it up that we pass that field along to Mortech and any other mortgage lead system.  Preferably we'd use a standard field, like filter_name  so that this customer gets the data they need and the next customer tells Mortech "My leads come through LC" and Mortech uses our mapping id and maps everything to the right place and the customer adds Velocify and Mortech to their flow and they're done and get all the information they need.

If they really really want to map it to some one-off thing, then we can do that and make a new field or with the custom stuff Alex is proposing they could map it themselves.  But it's so much better if we suck up the pain on the initial setups and get things such that they are drag and drop simple for the next mortgage client we land.

**Comment by kcaponeAP** [comment]
After some Mortech research, there are no fields specifically prefixed with anything LendingTree oriented. What would be ideal would be allow the integration to just deliver to filter ID? We wouldn't necessarily be able to lock this to a particular LCN variable since each vendor appears to use it differently..

Attached is the fields from a screen grab from Mortech. PII  removed. Please look to page one, borrower info. This is the only section of the CRM to route data from a lead to that is specific to ID / Product Name. Etc. 
![prospect details](https://cloud.githubusercontent.com/assets/8238417/5707424/7018ccae-9a4e-11e4-97a6-e047ccb1dfa7.jpg)

**Comment by poppop51** [comment]
Restating the problem: Considering leads purchased from Lending tree by two different Mortech customers. For Mortech Customer A, filterID may be populated from one particular Tree field, and for Mortech Customer B, filterID may be populated from a different Tree field. So is there a compelling reason why the filter_id field can't be added to the Mortech integration such that any LCN field can be mapped to it?

**Comment by zalary** [comment]
Why is there a disparity between which fields users capture as filter id?   Are there 2 fields that are commonly used?  More?  Can Mortech add new fields on their side that could accommodate a specific LendingTree filter id?

We can add this as a field which has to be mapped, but we would much much prefer that we make our integrations work such that there are sensible defaults and that customers don't have to set up mappings

**Comment by poppop51** [comment]
While I don't know first hand, let me take a guess: Let's say that a customer wants to be able to route/filter/sort/process their leads within Mortech according to some criteria that they (customer) can specify. The filter_id field holds the value which that automation evaluates. One client may want to filter/route/sort/process based on the ZIP code, another perhaps the phone, or whatever. Plus, a given Mortech customer may want to be able to change the parameter they use for that filtering/routing/sorting automation.
Whatever the reason, the field is there and apparently is intended to be flexibly populated. Beyond that, this customer needs this done.

**Comment by zalary** [comment]
The question I have is not the ability to let people map whatever they want - once we build the field, they can certainly do that.  My question is "Is there some sensible default that most customers might want to use here"  Be that lendingtree.filter_id or something else.  

If the answer is "No" then I'll just build it and it will be blank and every user will have to configure it or it will be blank.  It seems like having a default value if there is a sensible one makes more sense than building a field that every user has to know to configure, but *shrug* maybe not.

**Comment by kcaponeAP** [comment]
I have a note into my contact at Mortech to see a sample of what a range of vendors uses for the filter_id field. May help shed some light.

**Comment by kcaponeAP** [comment]
Well we do have confirmation from Mortech to change the following **only** for LendingTree leads.

"Filter_ID is always Filter_Name for LendingTree leads"

Is this acceptable @zalary?

**Comment by zalary** [comment]
in production as of January 20 2015
