### ISSUE TITLE
Please correct the LoanPurpose field

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-mortech#22]
We need to account for the following:

0 = Purchase, 
1 = Refinance
2 = Cashout Refinance
3 = HELOC

We are currently sending: ... &LoanPurpose=Refinance ... This does not work and all the leads are being sent as Purchase, which is the default in Mortech. Can someone please fix this ASAP. Client is unhappy and live with Mortech. 

https://next.leadconduit.com/events/54d0efb6a0605e4516e20042?event_id=54d0efb6a0605e4516e20047&type=source&start=2015-02-01&end=2015-02-28

Client name is 'P'

**Comment by kcaponeAP** [comment]
https://activeprospect.zendesk.com/agent/tickets/6829

**Comment by kcaponeAP** [comment]
Mortech documentation: https://drive.google.com/drive/#folders/0B36C7G4bQKsATm5sNnlraG5Za2s

**Comment by cgrayson** [comment]
According to the [docs for mortgage.loan.purpose](http://docs.leadconduit.com/fields?q=loan%20purpose) (and a quick scan of inbound mortgage integration code), it can be set to "refi", "purchase", or "equity". So as this will be coded, leads may get `0`, `1`, or `3`, but won't ever get `2` (for "Cashout Refinance"). Is that okay, or is that another problem to dig into?

**Comment by cgrayson** [comment]
@kcaponeAP this is ready to go, pending your answer to the above question.

**Comment by kcaponeAP** [comment]
I am fine with omitting cash out refinance. We have not seen leads come through with that as an option. Purchase and Refi are the only options we've seen at the moment come through on leads.

**Comment by cgrayson** [comment]
Fixed in 1.1.1

**Comment by kcaponeAP** [comment]
tyvm
